CREATE TABLE InterviewBookUser (
	ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	FirstName VARCHAR(100),
	LastName VARCHAR(150),
	PhoneNumber VARCHAR(25),
	DOB VARCHAR(25),
	Email VARCHAR(100),
	HockeyTeamID VARCHAR(100),
	PepsiOrCoke VARCHAR(25)
)

